sudo: required
dist: xenial
language: node_js
node_js:
  - '10.15.3'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

cache:
  directories:
  - node_modules
  - $HOME/.npm/_prebuilds
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

services:
  - xvfb

stages:
  - check
  - name: deploy mw
    if: branch = ghost-2.4
  - name: deploy linux
    if: branch = ghost-2.4

jobs:
  include:
    - stage: check
      script:
        - export TRUE_COMMIT_MESSAGES=$(git log --oneline -2 | grep "+build")
        - export TRUE_COMMIT=$(echo $TRUE_COMMIT_MESSAGES | awk '{print $1}')
        - echo $TRUE_COMMIT_MESSAGES
        - if [[ $TRUE_COMMIT_MESSAGES == *"+latest"* ]]; then yarn add https://github.com/ghost-coin/ghost-market; fi;
        - echo 'Build Dist' && echo -en 'travis_fold:start:script.build\\r'
        - yarn build --base-href="./"
        - echo -en 'travis_fold:end:script.build\\r'
        - echo 'Lint Codebase' && echo -en 'travis_fold:start:script.lint\\r'
        - yarn run lint
        - echo -en 'travis_fold:end:script.lint\\r'
        - echo 'Test Codebase' && echo -en 'travis_fold:start:script.test\\r'
        - yarn run travis:test
        - echo -en 'travis_fold:end:script.test\\r'
    - stage: deploy mw
      os: osx
      osx_image: xcode11.7
      script:
        - npm run deploy-mw
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: deploy linux
      os: linux
      dist: trusty
      before_script:
        - sudo apt-get install --no-install-recommends -y rpm
      script:
        - npm run deploy-linux

# Disable coveralls for now
# after_script:
#   - npm run coveralls

#deploy:
#  - provider: releases
#    api-key:
#      secure: <>
#    file:
#      - $TRAVIS_BUILD_DIR/dist.zip
#      - $TRAVIS_BUILD_DIR/dist.zip.sha256sum.txt
#    overwrite: true
#    on:
#      tags: true
